name: Generate package

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          cache: 'pip' # caching pip dependencies
          
      - name: Install python requirements
        working-directory: ${{ github.event.repository.name }}
        run: |
          pwd
          ls
          echo "${{ github.workspace }}"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install --upgrade build
          python -m build

      - name: Publish
        run: | 
          cd ${{ github.event.repository.name }}/
          find .
          gh release create ${{github.ref_name}} dist/r3threatmodeling-0.1.0-py3-none-any.whl
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
            
